language: python
python:
- 2.7
- 3.6
before_install:
- "! grep -R SKELETON | grep -v grep"
install:
- pip install -r requirements-dev.txt
- pip install coveralls pytest-cov
script:
- python setup.py checkdocs
- py.test --cov pyinthesky/
- py.test --cov pyinthesky/
- sphinx-build -W docs/ build/docs/
- pylint --disable=W pyinthesky/
after_script:
- flake8
- pylint pyinthesky/
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
  user: amc6010
  distributions: dists
  password:
    secure: DfAkleDON3RuDTus2b17xg8NfzyDPBmlE+ye08+fYQGKbFfWjClRehy/vFmKe6yR5cLFKt42zj83V31bllEppO87AbZmjd6bZImtAFw0MhOZi3ChwbrwoHz1cbVo5Z4jkKH2jTFedE72VFIWFx32fFdMDd9x3Js/a4kMQrq1WTo=
after_success:
- coveralls
